# Colors (Tangoish)
# Note: Orange is used in place of Cyan
colors:
  primary:
    background: '#2e3436'
    foreground: '#eeeeec'

  # Normal colors
  normal:
     black:   '#2e3436'
     red:     '#cc0000'
     green:   '#73d216'
     yellow:  '#edd400'
     blue:    '#3465a4'
     magenta: '#75507b'
     cyan:    '#06989a'
     white:   '#d3d7cf'

  # Bright colors
  bright:
     black:   '#555753'
     red:     '#ef2929'
     green:   '#8ae234'
     yellow:  '#fce94f'
     blue:    '#729fcf'
     magenta: '#ad7fa8'
     cyan:    '#34e2e2'
     white:   '#eeeeec'
font:
  bold:
    family: 'Source Code Pro'
    style: 'Bold Italic'
  normal:
    family: 'Source Code Pro'
    style: 'Medium Italic'
